name: release-check

on:
  workflow_dispatch:
  push:
    paths:
      - "go.*"
      - "**/*.go"
      - ".goreleaser.yml"
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".goreleaser.yml"

env:
  GO_VERSION: '1.23.1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Release Binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          install-only: true
      - name: Run goreleaser check
        run: goreleaser check
