name: release-check

on:
  workflow_dispatch:
  push:
    paths:
      - "go.*"
      - "**/*.go"
      - ".goreleaser.yml"
      - ".github/workflows/release-check.yml"
  pull_request:
    paths:
      - "go.*"
      - "**/*.go"
      - ".goreleaser.yml"
      - ".github/workflows/release-check.yml"

env:
  GO_VERSION: '1.23.1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: goto-bus-stop/setup-zig@v2
      - name: Set output
        id: macos-sdk
        run: echo "path=$(xcrun --show-sdk-path)" >> $GITHUB_OUTPUT
      - name: Release Binaries
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          install-only: true
      - name: goreleaser check and build
        run: |
          goreleaser check
          goreleaser build --snapshot --clean
        env:
          SDK_PATH: ${{ steps.macos-sdk.outputs.path }}
