name: release-check

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go.*"
      - "**/*.go"
      - ".goreleaser.yml"
  pull_request:
    paths:
      - ".goreleaser.yml"

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run release dry run
        run: |
          make release-dry-run
